name = "TianJiClient"
author = "comp500"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f87c2bb59abb1ae64bfaf5963483492353dd711406ef0650bfe19f702d40259"

[versions]
minecraft = "1.19.4"
fabric = "0.15.10"
